version: 2

models:
  - name: stg_distribution_centers
    description: "Staging model for distribution centers"
    columns:
      - name: id
        description: "The primary key for the distribution centers table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the distribution center"
      - name: latitude
        description: "Latitude of the distribution center"
      - name: longitude
        description: "Longitude of the distribution center"

  - name: stg_events
    description: "Staging model for events"
    columns:
      - name: id
        description: "The primary key for the events table"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The user associated with the event"
      - name: created_at
        description: "Timestamp when the event was created"

  - name: stg_inventory_items
    description: "Staging model for inventory items"
    columns:
      - name: id
        description: "The primary key for the inventory items table"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "The ID of the product"
      - name: created_at
        description: "Timestamp when the inventory item was created"
      - name: sold_at
        description: "Timestamp when the inventory item was sold"

  - name: stg_order_items
    description: "Staging model for order items"
    columns:
      - name: id
        description: "The primary key for the order items table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "The ID of the order"
      - name: product_id
        description: "The ID of the product in the order"
      - name: sale_price
        description: "The sale price of the order item"

  - name: stg_orders
    description: "Staging model for orders"
    columns:
      - name: order_id
        description: "The primary key for the orders table"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The user who placed the order"
      - name: created_at
        description: "Timestamp when the order was created"

  - name: stg_products
    description: "Staging model for products"
    columns:
      - name: id
        description: "The primary key for the products table"
        tests:
          - unique
          - not_null
      - name: name
        description: "The name of the product"
      - name: category
        description: "The category of the product"

  - name: stg_users
    description: "Staging model for users"
    columns:
      - name: id
        description: "The primary key for the users table"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "The first name of the user"
      - name: last_name
        description: "The last name of the user"
      - name: email
        description: "The email of the user"
      - name: created_at
        description: "Timestamp when the user was created"

  - name: int_user_orders
    description: "Intermediate model for user orders"
    columns:
      - name: user_id
        description: "The ID of the user"
      - name: order_id
        description: "The ID of the order"
      - name: order_status
        description: "The status of the order"
      - name: order_created_at
        description: "Timestamp when the order was created"

  - name: int_product_inventory
    description: "Intermediate model for product inventory"
    columns:
      - name: product_id
        description: "The ID of the product"
      - name: inventory_item_id
        description: "The ID of the inventory item"
      - name: product_name
        description: "The name of the product"
      - name: distribution_center_name
        description: "The name of the distribution center"

  - name: int_order_sales
    description: "Intermediate model for order sales"
    columns:
      - name: order_item_id
        description: "The ID of the order item"
      - name: order_id
        description: "The ID of the order"
      - name: sale_price
        description: "The sale price of the order item"
      - name: product_name
        description: "The name of the product"
      - name: user_id
        description: "The ID of the user who placed the order"

  - name: dim_users
    description: "Dimension model for users"
    columns:
      - name: user_id
        description: "The ID of the user"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "The first name of the user"
      - name: last_name
        description: "The last name of the user"
      - name: email
        description: "The email of the user"

  - name: dim_products
    description: "Dimension model for products"
    columns:
      - name: product_id
        description: "The ID of the product"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "The name of the product"
      - name: product_category
        description: "The category of the product"
      - name: distribution_center_name
        description: "The name of the distribution center"

  - name: dim_orders
    description: "Dimension model for orders"
    columns:
      - name: order_id
        description: "The ID of the order"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The ID of the user who placed the order"
      - name: order_status
        description: "The status of the order"
      - name: order_created_at
        description: "Timestamp when the order was created"

  - name: dim_inventory_items
    description: "Dimension model for inventory items"
    columns:
      - name: inventory_item_id
        description: "The ID of the inventory item"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "The ID of the product"
      - name: product_name
        description: "The name of the product"
      - name: distribution_center_name
        description: "The name of the distribution center"

  - name: fct_sales
    description: "Fact model for sales transactions"
    columns:
      - name: order_item_id
        description: "The ID of the order item"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "The ID of the order"
      - name: user_id
        description: "The ID of the user who placed the order"
      - name: product_id
        description: "The ID of the product"
      - name: sale_price
        description: "The sale price of the order item"
